# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "3.5"

services:
  hub-db:
    image: postgres:10.5
    container_name: jupyterhub-db
    restart: always
    environment:
      POSTGRES_DB: jupyterhub
    env_file:
      - secrets/postgres.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - jupyterhub

  hub:
    depends_on:
      - hub-db
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyterhub_img
      args:
        JUPYTERHUB_VERSION: 1.0.0
    restart: always
    #image: jupyterhub
    container_name: jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      #- "data:${DATA_VOLUME_CONTAINER}"
    ports:
      - "443:443"
      - "8008:8000"
    links:
      - hub-db
    networks:
      - jupyterhub
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub
      # JupyterHub will spawn this Notebook image for users
      # DOCKER_NOTEBOOK_IMAGE: jupyterhub/singleuser
      #DOCKER_NOTEBOOK_IMAGE: jupyter/datascience-notebook
      DOCKER_NOTEBOOK_IMAGE: jupyterlab_img
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /notebooks
      POSTGRES_DB: jupyterhub
      POSTGRES_HOST: hub-db
      POSTGRES_PASSWORD: jupyterhub_pass
      POSTGRES_USER: jupyterhub
      POSTGRES_PORT: 5432
      #env_file:
        #- secrets/postgres.env
        #- secrets/oauth.env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  jupyterhub_data:
  jupyterhub_db:
  db:
    #data:
    #  external:
    #    name: jupyterhub_data
    #db:
    #  external:
    #    name: jupyterhub_db

networks:
  jupyterhub:
    name: jupyterhub
#default:
#  external:
#    name: jupyterhub
