FROM jupyterhub/jupyterhub:1.2

# RUN wget https://raw.githubusercontent.com/jupyterhub/jupyterhub/0.9.3/examples/cull-idle/cull_idle_servers.py

RUN pip install \
    dockerspawner==0.10.0 \
    jhub_cas_authenticator==1.0.0 \
    oauthenticator==0.8.* \
    jupyterhub-dummyauthenticator==0.3.1 \
    psycopg2-binary==2.8.6 

COPY jupyterhub_config.py .
